### ISSUE TITLE
Error for Glyphs 1108

### ISSUE THREAD

**Issue by weiweihuanghuang** [Tosche/Waterfall#3]
```
Traceback (most recent call last):
  File "GlyphsApp/plugins.py", line 831, in loadPlugin
  File "/Users/weihuang/Library/Application Support/Glyphs/Repositories/Waterfall/Waterfall.glyphsPlugin/Contents/Resources/plugin.py", line 254, in start
    Glyphs.menu[WINDOW_MENU].append(newMenuItem)
NameError: global name 'WINDOW_MENU' is not defined
```

cc @schriftgestalt

**Comment by schriftgestalt** [comment]
That should be fixed already. Please get the latest version.
